import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.HashMap;
import java.util.Map;

public class BalonyPageServer {
    public static void main(String[] args) throws IOException {
        HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
        server.createContext("/", new PageHandler());
        server.setExecutor(null);
        System.out.println("Server started at http://localhost:8080");
        server.start();
    }

    private static class PageHandler implements HttpHandler {
        private final String htmlContent = "<!DOCTYPE html>\n"
                + "<html lang=\"uk\" class=\"scroll-smooth\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <meta name=\"robots\" content=\"index, follow\">\n"
                + "    <meta name=\"description\" content=\"Сертифікація балонів та балончиків в Україні. Професійний супровід та експертиза від ТОВ СП «ТОВАРИСТВО ТЕХНІЧНОГО НАГЛЯДУ ДІЕКС».\">\n"
                + "    <link rel=\"icon\" href=\"logo TC DIEX.jpg\" type=\"image/jpeg\">\n"
                + "    <meta name=\"keywords\" content=\"сертифікація балонів, балончики, газові балони, сертифікація продукції, оцінка відповідності\">\n"
                + "    <title>ТОВ СП «ТОВАРИСТВО ТЕХНІЧНОГО НАГЛЯДУ ДІЕКС» — Сертифікація балонів/балончиків</title>\n"
                + "    <script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script>\n"
                + "    <style>\n"
                + "        .hero-section { position: relative; overflow: hidden; }\n"
                + "        .hero-section::before {\n"
                + "            content: '';\n"
                + "            position: absolute;\n"
                + "            inset: 0;\n"
                + "            background: radial-gradient(circle at top left, rgba(99,102,241,0.18), transparent 32%), radial-gradient(circle at bottom right, rgba(129,140,248,0.16), transparent 28%);\n"
                + "            pointer-events: none;\n"
                + "        }\n"
                + "        #particleCanvas {\n"
                + "            position: absolute;\n"
                + "            inset: 0;\n"
                + "            width: 100%;\n"
                + "            height: 100%;\n"
                + "            z-index: 0;\n"
                + "            pointer-events: none;\n"
                + "        }\n"
                + "        .modal {\n"
                + "            display: none;\n"
                + "            position: fixed;\n"
                + "            inset: 0;\n"
                + "            background: rgba(0, 0, 0, 0.5);\n"
                + "            z-index: 40;\n"
                + "            align-items: center;\n"
                + "            justify-content: center;\n"
                + "            opacity: 0;\n"
                + "            transition: opacity 300ms ease;\n"
                + "        }\n"
                + "        .modal.show {\n"
                + "            display: flex;\n"
                + "            opacity: 1;\n"
                + "        }\n"
                + "        .modal-content {\n"
                + "            background: white;\n"
                + "            border-radius: 1rem;\n"
                + "            padding: 2rem;\n"
                + "            max-width: 28rem;\n"
                + "            width: 90%;\n"
                + "            box-shadow: 0 20px 25px rgba(0, 0, 0, 0.15);\n"
                + "            transform: scale(0.95);\n"
                + "            transition: transform 300ms ease;\n"
                + "        }\n"
                + "        .modal.show .modal-content {\n"
                + "            transform: scale(1);\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body class=\"bg-gray-50 text-gray-800 font-sans antialiased\">\n"
                + "    <header class=\"sticky top-0 bg-white/80 backdrop-blur-md shadow-sm z-50\">\n"
                + "        <div class=\"max-w-6xl mx-auto px-4 py-4 flex justify-between items-center\">\n"
                + "            <div class=\"flex items-center gap-3\">\n"
                + "                <a href=\"https://diex.org.ua\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"inline-flex items-center gap-3 rounded-full bg-white/90 border border-indigo-100 px-4 py-2 shadow-sm hover:bg-indigo-50 transition\">\n"
                + "                    <img src=\"logo TC DIEX.jpg\" alt=\"TC DIEX логотип\" class=\"h-12 w-15 rounded-xl bg-white shadow-sm\" />\n"
                + "                </a>\n"
                + "                <a href=\"http://www.tuev-dieks.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"hidden sm:inline-flex items-center rounded-full bg-indigo-50 text-indigo-700 px-3 py-2 text-sm font-semibold border border-indigo-100 shadow-sm hover:bg-indigo-100 transition\">\n"
                + "                    <img src=\"логотип отн.png\" alt=\"Другой логотип\" class=\"h-12 w-18 rounded-xl bg-white shadow-sm\" />\n"
                + "                </a>\n"
                + "            </div>\n"
                + "                <nav class=\"space-x-6 hidden sm:block\">\n"
                + "                    <a href=\"#about\" class=\"hover:text-indigo-600 transition\">Про послугу</a>\n"
                + "                    <a href=\"#cta\" class=\"hover:text-indigo-600 transition\">Контакти</a>\n"
                + "                </nav>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </header>\n"
                + "\n"
                + "    <section class=\"hero-section relative max-w-6xl mx-auto px-4 py-20 text-center sm:text-left sm:flex sm:items-center sm:justify-between gap-8\">\n"
                + "        <canvas id=\"particleCanvas\"></canvas>\n"
                + "        <div class=\"relative z-10 sm:w-1/2 space-y-6\">\n"
                + "            <span class=\"inline-flex items-center justify-center rounded-full px-4 py-1 text-sm font-semibold tracking-[0.24em] uppercase bg-indigo-600 text-white\">Професійна сертифікація</span>\n"
                + "            <h1 class=\"text-4xl sm:text-5xl font-extrabold text-gray-900 leading-tight\">\n"
                + "                Сертифікація <span class=\"text-indigo-600\">балонів та балончиків (картриджів)</span>\n"
                + "            </h1>\n"
                + "            <p class=\"text-lg text-gray-600\">\n"
                + "                Повний супровід процедури сертифікації та інспектування  (перевірки) газових балонів та балончиків відповідно до вимог українського та європейського законодавства.\n"
                + "            </p>\n"
                + "            <div class=\"pt-2\">\n"
                + "                <a href=\"TANK1.Doc\" download class=\"inline-block bg-indigo-600 text-white font-medium px-8 py-3 rounded-lg shadow-md hover:bg-indigo-700 transition transform hover:-translate-y-0.5\">\n"
                + "                    Заявка на сертифікацію\n"
                + "                </a>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "        <div class=\"relative z-10 sm:w-3/5 flex justify-center sm:justify-end\">\n"
                + "            <div class=\"relative w-full max-w-[48rem] rounded-[2rem] bg-white/90 border border-indigo-100 shadow-[0_80px_80px_rgba(99,102,241,0.12)] overflow-hidden px-6 py-6 sm:px-8 sm:py-8\">\n"
                + "                <div class=\"absolute -left-30 -top-10 w-36 h-36 rounded-full bg-indigo-100/80 blur-3xl\"></div>\n"
                + "                <div class=\"absolute -right-30 -bottom-12 w-44 h-88 rounded-full bg-sky-100/80 blur-3xl\"></div>\n"
                + "                <div class=\"relative mx-auto w-full max-w-[42rem]\">\n"
                + "                    <img src=\"GAZ balun.jpg\" alt=\"Газовый баллон и балончик\" class=\"w-full h-auto rounded-3xl shadow-xl border border-slate-200 bg-white\" />\n"
                + "                </div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </section>\n"
                + "\n"
                + "    <section id=\"about\" class=\"py-16 bg-white\">\n"
                + "        <div class=\"max-w-6xl mx-auto px-4\">\n"
                + "            <h2 class=\"text-3xl font-bold text-gray-900 mb-8\">Сертифікація балонів та балончиків</h2>\n"
                + "            <div class=\"space-y-8 text-gray-600\">\n"
                + "                 <div class=\"rounded-3xl bg-indigo-50 p-8 border border-indigo-100\">\n"
                + "                    <h3 class=\"text-2xl font-semibold text-gray-900 mb-4\">Послуги ТОВ СП «ТОВАРИСТВО ТЕХНІЧНОГО НАГЛЯДУ ДІЕКС»</h3>\n"
                + "                    <p class=\"leading-8 mb-4\">\n"
                + "                        Ми надаємо повний комплекс професійних послуг з оцінки та переоцінки відповідності, періодичного інспектування, для наступного обладнання:\n"
                + "                    </p>\n"
                + "                    <ul class=\"list-disc pl-6 space-y-3 text-gray-600\">\n"
                + "                        <li>балони (Технічний огляд балонів), кріоциліндри, трубки, барабани під тиском, закриті криогенні посудини, в'язки балонів і аварійні посудини під тиском;</li>\n"
                + "                        <li>ємності малі, що містять газ; газові балончики (картриджі) UN 2037 (цангові, різьбові пробивні та інші);</li>\n"
                + "                        <li>Клапани (вентилі) та інше обладнання у разі необхідності</li>\n"
                + "                    </ul>\n"
                + "                    <p class=\"mt-6 leading-8 text-gray-600\">\n"
                + "                        Сертифікація та інспектування здійснюється відповідно до вимог Технічного регламенту рухомого обладнання, що працює під тиском, затвердженого Постановою КМУ № 536 від 04.07.2018, а саме:\n"
                + "                    </p>\n"
                + "                    <ul class=\"space-y-2 text-gray-600 list-disc pl-6\">\n"
                + "                        <li>глави 6.2 додатка А до <a href=\"https://zakon.rada.gov.ua/laws/show/994_217\" class=\"text-indigo-600 hover:underline\">Європейської Угоди про міжнародне дорожнє перевезення небезпечних вантажів (ДОПНВ)</a>;</li>\n"
                + "                        <li>глави 6.1 додатка до <a href=\"https://zakon.rada.gov.ua/laws/show/994_169\" class=\"text-indigo-600 hover:underline\">Європейської угоди про міжнародне перевезення небезпечних вантажів внутрішніми водними шляхами (ВОПНВ)</a>;</li>\n"
                + "                        <li>глави 6.2 <a href=\"https://zakon.rada.gov.ua/laws/show/994_291\" class=\"text-indigo-600 hover:underline\">додатка С</a> до <a href=\"https://zakon.rada.gov.ua/laws/show/994_291\" class=\"text-indigo-600 hover:underline\">Конвенції про міжнародні залізничні перевезення (КОТІФ)</a>.</li>\n"
                + "                    </ul>\n"
                + "                </div>\n"
                + "                <div class=\"rounded-3xl bg-white p-8 border border-gray-100 shadow-sm\">\n"
                + "                    <h3 class=\"text-2xl font-semibold text-gray-900 mb-4\">Що ви отримуєте</h3>\n"
                + "                    <p class=\"leading-8 mb-4\">\n"
                + "                        За результатами успішного проведення робіт <strong>ТОВ СП «ТОВАРИСТВО ТЕХНІЧНОГО НАГЛЯДУ ДІЕКС»</strong> видає заявнику:\n"
                + "                    </p>\n"
                + "                    <ul class=\"list-disc pl-6 space-y-3 text-gray-600\">\n"
                + "                        <li><strong>Сертифікат відповідності</strong></li>\n"
                + "                <li><strong>Свідоцтво про перевірку</strong></li>\n"
                + "                        <li><strong>Маркування балончиків</strong></li>\n"
                + "                        <li><strong>Запис в паспорт обладнання на відповідність вимогам НПАОП 0.00-1.81-18. Після завершення технічного огляду фахівець робить запис у паспорті (або іншому експлуатаційному документі) балону про результати огляду, дозволені параметри експлуатації, строк наступного технічного огляду, свої прізвище, ім’я та по батькові, номер та строк дії посвідчення експерта, підтверджуючи запис підписом.</strong></li>\n"
                + "                    </ul>\n"
                + "                    <p class=\"mt-6 leading-8 text-gray-600\">\n"
                + "                        Після завершення технічного огляду фахівець робить запис у паспорті (або іншому експлуатаційному документі) устаткування про результати огляду, дозволені параметри експлуатації, строк наступного технічного огляду, свої прізвище, ім’я та по батькові, номер та строк дії посвідчення експерта, підтверджуючи запис підписом.\n"
                + "                    </p>\n"
                + "                </div>\n"
                + "                <div class=\"rounded-3xl bg-indigo-50 p-6 border border-indigo-100\">\n"
                + "                    <h3 class=\"text-2xl font-semibold text-gray-900 mb-3\">Обов’язкова вимога для обігу та експлуатації</h3>\n"
                + "                    <p class=\"text-gray-700 leading-7\">\n"
                + "                        Оцінка відповідності (інспектування/перевірка) вимогам Технічного регламенту рухомого обладнання, що працює під тиском, є <strong>обов’язковою вимогою</strong> для його експлуатації і обігу на ринку України.\n"
                + "                    </p>\n"
                + "                    <p class=\"text-gray-700 leading-7 mt-3\">\n"
                + "                        Усе рухоме обладнання що працює під тиском має відповідати нормам, розробленим на основі <strong>Директиви 2010/35/ЄС</strong> Європейського Парламенту та Ради. від 16 червня 2010 р.\n"
                + "                    </p>\n"
                + "                </div>\n"
                + "                <strong></strong>\n"
                + "                <div class=\"rounded-3xl bg-indigo-50 p-8 border border-indigo-100\">\n"
                + "                    <p class=\"text-base leading-8\">\n"
                + "                        <strong>ОРГАН З ІНСПЕКТУВАННЯ ТОВ СП «ТОВАРИСТВО ТЕХНІЧНОГО НАГЛЯДУ ДІЕКС»</strong> акредитований Національним агентством з акредитації України на інспектування відповідно до <strong>ДСТУ EN ISO/IEC 17020</strong>, атестат про акредитацію № 70001, чинний до 06.11.2028 р.\n"
                + "                        <a href=\"Atestat gaz balun.jpg\" target=\"_blank\" class=\"inline-block ml-3 mt-2 bg-indigo-600 text-white font-semibold px-3 py-1 rounded-lg shadow-sm hover:bg-indigo-700 transition\">Переглянути атестат</a>\n"
                + "                    </p>\n"
                + "                </div>\n"
                + "                \n"
                + "                <div class=\"rounded-3xl bg-gray-50 p-8 border border-gray-100\">\n"
                + "                    <h3 class=\"text-2xl font-semibold text-gray-900 mb-4\">Свідоцтво та повноваження</h3>\n"
                + "                    <p class=\"leading-8\">\n"
                + "                        Свідоцтво Мінекономіки від 01.10.2025 р. надає право на проведення робіт з оцінки відповідності (інспектування/перевірки) вимогам Технічного регламенту рухомого обладнання, що працює під тиском, затвердженого Постановою КМУ № 536 від 04.07.2018.\n"
                + "                        <a href=\"Svidotstvo gaz balun.pdf\" target=\"_blank\" class=\"inline-block ml-3 mt-2 bg-indigo-600 text-white font-semibold px-3 py-1 rounded-lg shadow-sm hover:bg-indigo-700 transition\">Переглянути свідоцтво</a>\n"
                + "                    </p>\n"
                + "                </div>\n"
                + "                <h2 class=\"text-3xl font-bold text-center text-gray-900 mb-12\">Як проходить сертифікація?</h2>\n"
                + "            <div class=\"grid grid-cols-1 md:grid-cols-4 gap-6\">\n"
                + "                <div class=\"p-6 bg-white rounded-2xl border border-gray-100 shadow-sm text-center\">\n"
                + "                    <div class=\"w-16 h-16 bg-indigo-600 rounded-full flex items-center justify-center mx-auto mb-4\">\n"
                + "                        <span class=\"text-2xl\">📄</span>\n"
                + "                    </div>\n"
                + "                    <h3 class=\"text-lg font-bold text-gray-900 mb-2\">Надсилаєте документи</h3>\n"
                + "                    <p class=\"text-sm text-gray-600\">Надішліть пакет документів для попередньої перевірки.</p>\n"
                + "                </div>\n"
                + "                <div class=\"p-6 bg-white rounded-2xl border border-gray-100 shadow-sm text-center\">\n"
                + "                    <div class=\"w-16 h-16 bg-indigo-600 rounded-full flex items-center justify-center mx-auto mb-4\">\n"
                + "                        <span class=\"text-2xl\">🔍</span>\n"
                + "                    </div>\n"
                + "                    <h3 class=\"text-lg font-bold text-gray-900 mb-2\">Проводимо аналіз</h3>\n"
                + "                    <p class=\"text-sm text-gray-600\">Аналізуємо документи та готуємо план сертифікації.</p>\n"
                + "                </div>\n"
                + "                <div class=\"p-6 bg-white rounded-2xl border border-gray-100 shadow-sm text-center\">\n"
                + "                    <div class=\"w-16 h-16 bg-indigo-600 rounded-full flex items-center justify-center mx-auto mb-4\">\n"
                + "                        <span class=\"text-2xl\">⚙️</span>\n"
                + "                    </div>\n"
                + "                    <h3 class=\"text-lg font-bold text-gray-900 mb-2\">Узгоджуємо випробування</h3>\n"
                + "                    <p class=\"text-sm text-gray-600\">Домовляємось про терміни та методи випробувань.</p>\n"
                + "                </div>\n"
                + "                <div class=\"p-6 bg-white rounded-2xl border border-gray-100 shadow-sm text-center\">\n"
                + "                    <div class=\"w-16 h-16 bg-indigo-600 rounded-full flex items-center justify-center mx-auto mb-4\">\n"
                + "                        <span class=\"text-2xl\">✅</span>\n"
                + "                    </div>\n"
                + "                    <h3 class=\"text-lg font-bold text-gray-900 mb-2\">Видаємо документи</h3>\n"
                + "                    <p class=\"text-sm text-gray-600\">Після успішної перевірки ви отримуєте офіційні документи.</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </section>\n"
                + "     <section id=\"features\" class=\"bg-white py-20 border-y border-gray-100\">\n"
                + "        <div class=\"max-w-6xl mx-auto px-4\">\n"
                + "            <h2 class=\"text-3xl font-bold text-center text-gray-900 mb-12\">Наші переваги</h2>\n"
                + "            <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\">\n"
                + "                <div class=\"p-6 bg-gray-50 rounded-xl border border-gray-100\">\n"
                + "                    <div class=\"w-12 h-12 bg-indigo-100 text-indigo-600 rounded-lg flex items-center justify-center font-bold text-lg mb-4\">1</div>\n"
                + "                    <h3 class=\"text-xl font-bold mb-2\">Швидкість</h3>\n"
                + "                    <p class=\"text-gray-600\">Наші сертифікати видаються швидко, щоб не затримувати ваш бізнес.</p>\n"
                + "                </div>\n"
                + "                <div class=\"p-6 bg-gray-50 rounded-xl border border-gray-100\">\n"
                + "                    <div class=\"w-12 h-12 bg-indigo-100 text-indigo-600 rounded-lg flex items-center justify-center font-bold text-lg mb-4\">2</div>\n"
                + "                    <h3 class=\"text-xl font-bold mb-2\">Клієнто-орієнтованість</h3>\n"
                + "                    <p class=\"text-gray-600\">Ми зосереджуємося на потребах наших клієнтів і надаємо персоналізовані рішення.</p>\n"
                + "                </div>\n"
                + "                <div class=\"p-6 bg-gray-50 rounded-xl border border-gray-100\">\n"
                + "                    <div class=\"w-12 h-12 bg-indigo-100 text-indigo-600 rounded-lg flex items-center justify-center font-bold text-lg mb-4\">3</div>\n"
                + "                    <h3 class=\"text-xl font-bold mb-2\">Якість</h3>\n"
                + "                    <p class=\"text-gray-600\">Ми прагнемо до найвищих стандартів якості у всіх наших послугах.</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </section>\n"
                + "    <section id=\"cta\" class=\"max-w-3xl mx-auto px-4 py-14 text-center\">\n"
                + "        <div class=\"bg-indigo-600 text-white rounded-2xl p-8 shadow-xl space-y-5\">\n"
                + "            <h2 class=\"text-2xl sm:text-3xl font-bold\">Готові розпочати?</h2>\n"
                + "            <p class=\"text-indigo-100 max-w-2xl mx-auto\">\n"
                + "                Залиште заявку, і ми надамо консультацію з підготовки документів та вибору оптимального шляху сертифікації вашої продукції.\n"
                + "            </p>\n"
                + "            <div class=\"flex flex-col sm:flex-row justify-center items-center gap-3 pt-4\">\n"
                + "                <a href=\"mailto:gas@tuev-dieks.com\" class=\"w-full sm:w-auto bg-white text-indigo-600 font-semibold px-6 py-2.5 rounded-lg hover:bg-indigo-50 transition\">\n"
                + "                    gas@tuev-dieks.com\n"
                + "                </a>\n"
                + "                <a href=\"tel:+380675617679\" class=\"w-full sm:w-auto bg-indigo-700 text-white font-semibold px-6 py-2.5 rounded-lg hover:bg-indigo-800 transition\">\n"
                + "                    +38 067-561-76-79\n"
                + "                </a>\n"
                + "                <button id=\"ctaCallBtn\" class=\"w-full sm:w-auto bg-white text-indigo-700 font-semibold px-6 py-2.5 rounded-lg border border-indigo-200 hover:bg-indigo-50 transition\">\n"
                + "                    Замовити дзвінок\n"
                + "                </button>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </section>\n"
                + "\n"
                + "    <footer class=\"bg-gray-900 text-gray-400 py-8 text-center text-sm border-t border-gray-800\">\n"
                + "        <p>&copy; 2026 ОТН DIEX. Всі права захищені.</p>\n"
                + "    </footer>\n"
                + "    <button id=\"floatingCallBtn\" class=\"fixed right-4 bottom-4 z-50 inline-flex items-center gap-2 rounded-full bg-indigo-600 px-5 py-3 text-white font-semibold shadow-2xl shadow-indigo-700/30 transition hover:bg-indigo-700 hover:-translate-y-0.5\">\n"
                + "        <span style=\"filter: brightness(0) invert(1);\">📞</span>\n"
                + "        <span>Замовити дзвінок</span>\n"
                + "    </button>\n"
                + "    <div id=\"callModal\" class=\"modal\">\n"
                + "        <div class=\"modal-content\">\n"
                + "            <div class=\"flex justify-between items-center mb-6\">\n"
                + "                <h2 class=\"text-2xl font-bold text-gray-900\">Замовити дзвінок</h2>\n"
                + "                <button id=\"closeModal\" class=\"text-gray-500 hover:text-gray-700 text-2xl leading-none\">×</button>\n"
                + "            </div>\n"
                + "            <form id=\"callForm\" action=\"https://formspree.io/f/xzdqbknr\" method=\"POST\" class=\"space-y-4\">\n"
                + "                <div>\n"
                + "                    <label for=\"name\" class=\"block text-sm font-medium text-gray-700 mb-1\">Ім'я</label>\n"
                + "                    <input type=\"text\" id=\"name\" name=\"name\" required class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none\" placeholder=\"Ваше ім'я\">\n"
                + "                </div>\n"
                + "                <div>\n"
                + "                    <label for=\"email\" class=\"block text-sm font-medium text-gray-700 mb-1\">Email</label>\n"
                + "                    <input type=\"email\" id=\"email\" name=\"email\" required class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none\" placeholder=\"your@email.com\">\n"
                + "                </div>\n"
                + "                <div>\n"
                + "                    <label for=\"phone\" class=\"block text-sm font-medium text-gray-700 mb-1\">Телефон</label>\n"
                + "                    <input type=\"tel\" id=\"phone\" name=\"phone\" required class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none\" placeholder=\"+380...\">\n"
                + "                </div>\n"
                + "                <div>\n"
                + "                    <label for=\"message\" class=\"block text-sm font-medium text-gray-700 mb-1\">Повідомлення</label>\n"
                + "                    <textarea id=\"message\" name=\"message\" rows=\"3\" class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none resize-none\" placeholder=\"Ваше повідомлення (опціонально)\"></textarea>\n"
                + "                </div>\n"
                + "                <button type=\"submit\" class=\"w-full bg-indigo-600 text-white font-semibold py-2.5 rounded-lg hover:bg-indigo-700 transition\">\n"
                + "                    Надіслати запит\n"
                + "                </button>\n"
                + "            </form>\n"
                + "        </div>\n"
                + "    </div>\n"
                + "    <script>\n"
                + "        document.addEventListener('DOMContentLoaded', () => {\n"
                + "            const modal = document.getElementById('callModal');\n"
                + "            const closeModal = document.getElementById('closeModal');\n"
                + "            const ctaCallBtn = document.getElementById('ctaCallBtn');\n"
                + "            const floatingCallBtn = document.getElementById('floatingCallBtn');\n"
                + "            const callForm = document.getElementById('callForm');\n\n"
                + "            const openModal = () => {\n"
                + "                modal.classList.add('show');\n"
                + "                document.body.style.overflow = 'hidden';\n"
                + "            };\n\n"
                + "            const closeModalFunc = () => {\n"
                + "                modal.classList.remove('show');\n"
                + "                document.body.style.overflow = '';\n"
                + "            };\n\n"
                + "            ctaCallBtn.addEventListener('click', openModal);\n"
                + "            floatingCallBtn.addEventListener('click', openModal);\n                + "            closeModal.addEventListener('click', closeModalFunc);\n\n"
                + "            modal.addEventListener('click', (e) => {\n"
                + "                if (e.target === modal) {\n"
                + "                    closeModalFunc();\n"
                + "                }\n"
                + "            });\n\n"
                + "            callForm.addEventListener('submit', () => {\n"
                + "                setTimeout(closeModalFunc, 500);\n"
                + "            });\n\n"
                + "            document.addEventListener('keydown', (e) => {\n"
                + "                if (e.key === 'Escape' && modal.classList.contains('show')) {\n"
                + "                    closeModalFunc();\n"
                + "                }\n"
                + "            });\n\n"
                + "            const canvas = document.getElementById('particleCanvas');\n"
                + "            if (!canvas) return;\n"
                + "            const ctx = canvas.getContext('2d');\n"
                + "            const particles = [];\n"
                + "            const particleCount = 30;\n"
                + "            const random = (min, max) => Math.random() * (max - min) + min;\n\n"
                + "            const resizeCanvas = () => {\n"
                + "                const ratio = window.devicePixelRatio || 1;\n"
                + "                canvas.width = canvas.clientWidth * ratio;\n"
                + "                canvas.height = canvas.clientHeight * ratio;\n"
                + "                ctx.setTransform(ratio, 0, 0, ratio, 0, 0);\n"
                + "            };\n\n"
                + "            class Particle {\n"
                + "                constructor() {\n"
                + "                    this.reset();\n"
                + "                }\n"
                + "                reset() {\n"
                + "                    this.x = random(0, canvas.clientWidth);\n"
                + "                    this.y = random(0, canvas.clientHeight);\n"
                + "                    this.radius = random(1.5, 4.5);\n"
                + "                    this.speed = random(0.15, 0.45);\n"
                + "                    this.angle = random(0, Math.PI * 2);\n"
                + "                    this.alpha = random(0.15, 0.5);\n"
                + "                    this.color = `rgba(99,102,241,${this.alpha})`;\n"
                + "                }\n"
                + "                update() {\n"
                + "                    this.x += Math.cos(this.angle) * this.speed;\n"
                + "                    this.y += Math.sin(this.angle) * this.speed;\n"
                + "                    if (this.x < -20 || this.x > canvas.clientWidth + 20 || this.y < -20 || this.y > canvas.clientHeight + 20) {\n"
                + "                        this.reset();\n"
                + "                        if (Math.random() > 0.5) {\n"
                + "                            this.x = random(0, canvas.clientWidth);\n"
                + "                            this.y = -10;\n"
                + "                        } else {\n"
                + "                            this.x = -10;\n"
                + "                            this.y = random(0, canvas.clientHeight);\n"
                + "                        }\n"
                + "                    }\n"
                + "                }\n"
                + "                draw() {\n"
                + "                    ctx.beginPath();\n"
                + "                    ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2);\n"
                + "                    ctx.fillStyle = this.color;\n"
                + "                    ctx.fill();\n"
                + "                }\n"
                + "            }\n\n"
                + "            const initParticles = () => {\n"
                + "                particles.length = 0;\n"
                + "                for (let i = 0; i < particleCount; i += 1) {\n"
                + "                    particles.push(new Particle());\n"
                + "                }\n"
                + "            };\n\n"
                + "            const animate = () => {\n"
                + "                ctx.clearRect(0, 0, canvas.clientWidth, canvas.clientHeight);\n"
                + "                particles.forEach((particle) => {\n"
                + "                    particle.update();\n"
                + "                    particle.draw();\n"
                + "                });\n"
                + "                requestAnimationFrame(animate);\n"
                + "            };\n\n"
                + "            window.addEventListener('resize', () => {\n"
                + "                resizeCanvas();\n"
                + "                initParticles();\n"
                + "            });\n\n"
                + "            resizeCanvas();\n"
                + "            initParticles();\n"
                + "            animate();\n"
                + "        });\n"
                + "    </script>\n"
                + "</body>\n"
                + "</html>";

        @Override
        public void handle(HttpExchange exchange) throws IOException {
            String path = URLDecoder.decode(exchange.getRequestURI().getPath(), StandardCharsets.UTF_8);
            if (path.equals("/") || path.equals("/balony") || path.equals("/balony.html") || path.equals("/balony java.html")) {
                sendResponse(exchange, htmlContent, "text/html; charset=UTF-8");
                return;
            }

            File root = new File(".").getCanonicalFile();
            File file = new File(root, path.substring(1));
            if (!file.getCanonicalPath().startsWith(root.getCanonicalPath()) || !file.exists() || file.isDirectory()) {
                sendResponse(exchange, "404 Not Found", "text/plain; charset=UTF-8", 404);
                return;
            }

            String contentType = guessContentType(file.getName());
            exchange.getResponseHeaders().set("Content-Type", contentType);
            exchange.sendResponseHeaders(200, file.length());
            try (OutputStream os = exchange.getResponseBody(); FileInputStream fis = new FileInputStream(file)) {
                byte[] buffer = new byte[8192];
                int count;
                while ((count = fis.read(buffer)) != -1) {
                    os.write(buffer, 0, count);
                }
            }
        }

        private void sendResponse(HttpExchange exchange, String response, String contentType) throws IOException {
            sendResponse(exchange, response, contentType, 200);
        }

        private void sendResponse(HttpExchange exchange, String response, String contentType, int statusCode) throws IOException {
            exchange.getResponseHeaders().set("Content-Type", contentType);
            byte[] bytes = response.getBytes(StandardCharsets.UTF_8);
            exchange.sendResponseHeaders(statusCode, bytes.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(bytes);
            }
        }

        private String guessContentType(String filename) {
            String lower = filename.toLowerCase();
            if (lower.endsWith(".html") || lower.endsWith(".htm")) return "text/html; charset=UTF-8";
            if (lower.endsWith(".css")) return "text/css; charset=UTF-8";
            if (lower.endsWith(".js")) return "application/javascript";
            if (lower.endsWith(".json")) return "application/json";
            if (lower.endsWith(".png")) return "image/png";
            if (lower.endsWith(".jpg") || lower.endsWith(".jpeg")) return "image/jpeg";
            if (lower.endsWith(".svg")) return "image/svg+xml";
            if (lower.endsWith(".pdf")) return "application/pdf";
            if (lower.endsWith(".doc") || lower.endsWith(".docx")) return "application/msword";
            return "application/octet-stream";
        }
    }
}
